import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import MotionProvider from "@/providers/MotionProvider";



const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
})


export const metadata: Metadata = {
  title: "GDG JOS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${inter.variable} ${outfit.className} antialiased`}
      >
        <MotionProvider>
          {children}
        </MotionProvider>
      </body>
    </html>
  );
}
